Repository meilisearch/landing, pull requests merged in 2022-10, with the labels that each got.

#497 removed every mentions of npm in contributing markdown
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#509 Add fallback fonts
  .storybook/preview-head.html
  src/blocks/Developer/Terminal/LeftColumn.js
  src/blocks/OpenSource.js
  src/components/InteractiveSearch.js
  src/components/Markdown.js
  src/components/Searchbox.js
  src/components/Typography.js
  src/pages/404.js
  src/pages/_document.js
  src/theme/fontFamily.js
  src/theme/index.js
Labels: maintenance

#511 Ensure PR 486 passes tests
  .env.example
  src/components/InteractiveSearch.js
  src/stories/Searchbox.stories.js
Labels: skip-changelog, maintenance

#521 Update cloud plans data
  data/pricing.js
  src/components/icons/Diamond.js
  src/components/icons/GraduationCap.js
  src/components/icons/Rocket.js
  src/components/icons/index.js
  src/components/icons/svg/diamond.svg
  src/components/icons/svg/graduation_cap.svg
  src/components/icons/svg/rocket.svg
Labels: maintenance

#522 Update pricing card component
  src/components/PricingCard.js
  src/stories/FullWidthCard.stories.js
  src/stories/IconCard.stories.js
  src/stories/PricingCard.stories.js
Labels: component, maintenance

#524 Ensure PR 513 passes tests
  src/blocks/Header/MobileHeader.js
  src/components/Lottie.js
  src/components/icons/Hamburger.js
  src/components/icons/index.js
  src/components/icons/svg/hamburger.svg
  src/lotties/hamburgerMenu.json
  src/stories/Dialog.stories.js
  src/stories/Icons.stories.js
Labels: maintenance

#525 Add card component
  src/blocks/Developer/Text.js
  src/blocks/Footer/Newsletter.js
  src/blocks/Step3/FirstSection.js
  src/blocks/Step3/SecondSection.js
  src/components/Card.js
  src/components/PricingCard.js
  src/stories/Card.stories.js
Labels: maintenance

#530 Update open source section
  src/blocks/Pricing/Column.js
  src/blocks/Pricing/OpenSource.js
  src/blocks/Pricing/index.js
Labels: maintenance

#531 Add hover & focus state on pricing cards
  src/blocks/Pricing/OpenSource.js
  src/blocks/Pricing/PayingPlans/Plan.js
  src/blocks/Pricing/PayingPlans/index.js
  src/blocks/PricingAssistant/Results.js
  src/components/PricingCard.js
  src/stories/PricingCard.stories.js
Labels: maintenance

#534 Clean result card component
  src/blocks/PricingAssistant/ResultCard.js
  src/blocks/PricingAssistant/Results.js
Labels: maintenance

#563 Remove .babelrc file
  .babelrc
  next.config.js
  package.json
  yarn.lock
Labels: maintenance
